### ISSUE TITLE
This is AWESOME

### ISSUE THREAD

**Issue by SuperJMN** [ipjohnson/Grace#101]
This isn't a DI container, it's THE DI CONTAINER.

Also, this isn't an issue, just a way to give you thanks for your great work. Keep it up, Ian!

I hope you're OK :) 

BTW, It seems I finally got my team use Grace. Woohoo!

**Comment by ipjohnson** [comment]
Hi Jose, 

Long time no see :) Thanks for the compliments. I'll send you an email here to shot the sh*t
