### ISSUE TITLE
BUG wrong child container locate behavior

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#122]
```csharp
var root = new DependencyInjectionContainer();
root.Configure(_ =>_.Export<FileLogListener>().AsKeyed<ILogListener>("file"));
var child = root.CreateChildScope(_ => _.ExportInstance<ILogListenerSettings>(new LogListenerSettings()));
var listener = child.Locate<ILogListener>("file");
```

FileLogListener depends on ILogListenerSettings
So...exception:
Grace.DependencyInjection.Exceptions.LocateException: Could not locate Type ILogListenerSettings

but child.Locate<ILogListenerSettings>() resolve normally with normal ILogListenerSettings instance.

**Comment by ipjohnson** [comment]
try this

```C#
root.Configure(
     _ =>_.Export<FileLogListener>().AsKeyed<ILogListener>("file").WithCtorParam<ILogListenerSettings>().IsDynamic());
```

**Comment by mcdis** [comment]
That's work, but in common case there can be many dependencies inside "FileLogListener". 
So it would complicated to maitance the code becouse I've to duplcate depencdencies (in ctor and in registration).
For me that's the base scenary...I create child container, throughout some bahaviors and resolve component. So during resolve the dependecies have to be resolved from child container.
I've checked StructureMap for this functional and StrucutreMap fail.


And I've got another Issues:
 - add some constraints to IFluentExportStrategyConfiguration<T> AsKeyed<TInterface>(object key);

**Comment by ipjohnson** [comment]
@mcdis if you want your default behavior to always be dynamic then you can change the constructor selection logic to be dynamic all the time with this.

```C#
var container = new DependencyInjectionContainer(c => c.Behaviors.ConstructorSelection = ConstructorSelectionMethod.Dynamic);
```

I'm not sure I follow the "Add Some constraints" comment. Could you elaborate?

**Comment by mcdis** [comment]
About constrains:
exists code:
`c.Configure(_ =>_.Export<ConsoleLogListener>().AsKeyed<IApp>("console"));`
No errors (static checking)
But ConsoleLogListener doesn't implement IApp at all.
For example in Unity:
 `public static IUnityContainer RegisterType<TFrom, TTo>(this IUnityContainer container, params InjectionMember[] injectionMembers) where TTo : TFrom`
The key: **where TTo : TFrom**
So that's add static checking.
At this moment I'm looking alternative to unity becouse no support/maintance.
And when I've started use the Grace there was some simple error:
I've used wrong call order: `_=>_.Export<IInterface>().As<Impl>()` but there was no error during code time. Becouse in Export<TTo>.As<TFrom> there no type constraint: where TTo:TFrom

**Comment by mcdis** [comment]
@ipjohnson thak you
`new DependencyInjectionContainer(c => c.Behaviors.ConstructorSelection = ConstructorSelectionMethod.Dynamic);`
That's work perfect.

**Comment by ipjohnson** [comment]
@mcdis there is a C# extensions similar to unity that has the constraints you want. It's just not possible with the `Export<T>` because of the way it's defined. 

```C#
c.Configure(_ => _.ExportAs<TImpl, TInterface>());
```

**Comment by mcdis** [comment]
But you can add constraint to As<>
```csharp
public interface IFluentExportStrategyConfiguration<T>
{
    IFluentExportStrategyConfiguration<T> As<TInterface>() where T:TInterface; // <--- where
}
```

**Comment by mcdis** [comment]
ExportAs - thank you. I didn't know
