### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#123]
Think about renaming:
- DependencyInjectionContainer -> Container or GraceContainer
- IInjectionScope -> IContainer or like thar
- CreateChildScope -> Create Child Contianer or NewChild or Child()
Make syntax like average...That's can make the Grace more popular and **decrease line length**.
At this moment:
`_c.CreateChildScope(_ => _.ExportFactory<ILogListenerSettings>(()=>settings))`
`Container = _container ?? new DependencyInjectionContainer();z`
but it can look more simple
`_c.Child(_ => _.ExportFactory<ILogListenerSettings>(()=>settings))`
`Container = _container ?? new GraceContainer();`

**Comment by ipjohnson** [comment]
While appreciate your ideas to make the code easier to read it will be massive breaking changes for existing users. 

At the moment I don't have much stomach for drastic changes as Grace was re-written last year from the ground up.

I'll leave this open for a bit to see what kind of traction it would get from other users.

**Comment by mcdis** [comment]
Don't need and love exists style
