### ISSUE TITLE
Chain configuration

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#124]
Think does it possible to make configuration more simple and more chainy (more compact):
example:
c - container
```csharp
c.Configure(_=>_.ExportAs<A,IA>()
  .ExportAs<B,IB>()
  .ExportAs<C,IC>());
```
another example
```csharp
c.ExportAs<B,IB>().ExportAs<C,IC>().ExportAs<A,IA>().Configure()
```

**Comment by ipjohnson** [comment]
Currently the way `ExportAs<T>` returns a configuration object that allows you to configure the lifestyle and other facets. 

I'd be open to adding another extension method that goes off of container or is named something else like Register

**Comment by mcdis** [comment]
May be add some .Configurate alias?
For example 
```csharp
IInjectionScope Cfg(this IInjectionScope _this, Action<IExportRegistrationBlock> _cfg);
```
or use another interface in IExportRegistrationBlock that provide chainy technique but inside it's work over IExportRegistrationBlock but syntax more compact

**Comment by ipjohnson** [comment]
I'm going to close this out as C# extensions can be used to simulate this.
