### ISSUE TITLE
Provide simple way to check is type registered

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#126]
In Unity there is IsRegistered(Type _t) method eixists.
Using them you can check does registration to type exitst.
IsRegistered check from child to parent containers.

**Comment by ipjohnson** [comment]
Hi @mcdis 

There is a method on the registration block called `IsExported` that should be what you are looking for

**Comment by ipjohnson** [comment]
@mcdis Did this work for you?

**Comment by mcdis** [comment]
Will try soon and answer

**Comment by ipjohnson** [comment]
As I haven't heard back that this doesn't work I'm closing the issue
