### ISSUE TITLE
Provide extensions to make proxy location simplier

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#127]
Register proxy location to another container.
In my case when the system is configurating some modules have to register global interfaces but part of behaviors are registered in child container. So, I need to resolve my interfaces with child container behaviors but after that I have to get acces from global. So in my case proxing is common way.

Example
```csharp
mainContainer.Configure(_ => _.ExportFactory(() => otherContainer.Locate<IUiLocalizedTextProvider>()).Lifestyle.Singleton());
```
In my case I know that proxied IUiLocalizedTextProvider can be cached so I use .Lifestyle.Singleton()

Syntax proposal:
a) 
```csharp
container.Configure(_=>_.Proxy<T>(otherContainer));
//.ExportFactory(() => otherContainer.Locate<T>()).Lifestyle.Singleton()
```

b)
```csharp
container.Configure(_=>_.ProxyAndCache<T>(otherContainer)); 
// .ExportFactory(() => otherContainer.Locate<T>()).Lifestyle.Singleton()
```

**Comment by ipjohnson** [comment]
@mcdis I this seems like some what of a niche extension. For the moment I'm going to recommend implementing them as C# extensions in your code base and if I get some more requests in we can look at formalizing the code into an extension library for Grace

**Comment by mcdis** [comment]
ok, that's the way I'm doing now

**Comment by ipjohnson** [comment]
I'm going to close this and a new issue can be created if it becomes a popular request
