### ISSUE TITLE
Change return type of Configure (maybe some extension on alias like .Cfg(_=>...) )

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#128]
At this momebt IInjectionScope::Configure returning void, so I can't create routine that create child, configure them and return in one line.
If Configure return IInjectionScope I can do this:
```csharp
IInjectionScope ConfigSuperBuper(this IShell _this)
 => _this.Container.CreateChildScope().Configure(_ =>_.ExportAs<A,IA>());
```
but I have to
```csharp
IInjectionScope ConfigSuperBuper(this IShell _this)
{
   var child = this.Container.CreateChildScope();
   child_.Configure(_ =>_.ExportAs<A,IA>());
   return child;
}
```

**Comment by ipjohnson** [comment]
@mcdis I'd be open to changing the return type on configure.

**Comment by ipjohnson** [comment]
I'm going to close this out in favor of each developer doing C# extensions to implement their own specific flavor for registration
