### ISSUE TITLE
Split nuget packages into interface part and implimentation

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#131]
Example of split:
- Grace
- Grace.Interface

That will allow reterget my nuget packages from Grace to Grace.Interface and will make my packages more durable to Grace changes. 
If my lib use only interop with containers and it targeted to interface it will independ to container creation or behavior

**Comment by ipjohnson** [comment]
@mcdis Interesting idea and one I'd like to keep on the table for version 7.0. As you say it will allow for more stable consumption of Grace

**Comment by mcdis** [comment]
May it's a good idea to split into 3 pieces:
- Grace.Interface
- Grace.Extensions
- Grace
Interface - minimal wireframe
Extensions - that's extensions based on Grace.Interface and simple extend sugar synatax
Grace - impl of interfaces and container creation logic

All syntax sugar based on Grace.Interface will live in Grace.Extensions

**Comment by ipjohnson** [comment]
For the moment I'm going to close this out.
