### ISSUE TITLE
Why does this anonymous method always return true?

### ISSUE THREAD

**Issue by cuteant** [ipjohnson/Grace#138]
https://github.com/ipjohnson/Grace/blob/fef365638fa012ecb9adea63b7998c179b9d1498/src/Grace/DependencyInjection/Impl/Expressions/DynamicConstructorExpressionCreator.cs#L237

**Comment by ipjohnson** [comment]
I think it's a bug and should return false, I'll take a look this weekend at fixing it and adding a use case. Thanks for finding that.

**Comment by greendimka** [comment]
Shouldn't the #138 be closed now? :)

**Comment by ipjohnson** [comment]
Good point, I'll close it now. Thanks.

**Comment by ipjohnson** [comment]
This is released in 6.3.1
