### ISSUE TITLE
Export factory to generics

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#139]
Hi!
How I can configure export factory to a generics type?
I want to bind ```ISomeGenericsInterface<T>``` to factory ```Func<T>``` method (single instance in container)

**Comment by ipjohnson** [comment]
@mcdis I'm not sure I completely follow can you post some examples of what you want to do?

**Comment by mcdis** [comment]
```csharp
container.Configure(_=>_.ExportFactory(typeof(ISomeGenericsInterface<>),_type=>FactoryMethod(_type)).Lifcycle.Singleton());

var a = container.Locate<ISomeGenericsInterface<MyResource>>();
// res = FactoryMethod(typeof(ISomeGenericsInterface<MyResource>));
var b = container.Locate<ISomeGenericsInterface<MyResource>>();
var isEq = object.ReferenceEquals(a,b); //isEq = true
```
In my case I know how to locate ISomeGenericsInterface<T> and the result have to be singleton.
But I don't know concrete types. So When ISomeGenericsInterface<T> locate the factory method have to be called and the result must cached (Singletone).

**Comment by mcdis** [comment]
Another words, I need a way to define factory which locate generic interface ```ISomeInterface<T>```

**Comment by ipjohnson** [comment]
Hi @mcdis 

There isn't anything specifically built in to do that but I believe you could get the behavior you are looking for using IMissingExportStrategyProvider. I'll see about writing something up this evening.

**Comment by ipjohnson** [comment]
@mcdis sorry took me a bit but here is the [final implementation](https://github.com/ipjohnson/Grace/blob/dev/tests/Grace.Tests/DependencyInjection/Generics/GenericFactoryTests.cs).

**Comment by ipjohnson** [comment]
@mcdis can I go a head and close this as completed?

**Comment by Adanaran** [comment]
Hi @ipjohnson
I have used your proposal above to create generic types through a method.
This works as expected, apart from when a type bound with this strategy is injected into another type. This can be solved by wrapping the created expression with a cast before returning it in line [146](https://github.com/ipjohnson/Grace/blob/029ca461b91f24243ceea12aa1a3d8b5669566d4/tests/Grace.Tests/DependencyInjection/Generics/GenericFactoryTests.cs#L146).
Code added:
```C#
expression = Expression.Convert(expression, activationType);
```

Test case:

```C#
public class Outer
{
    public ITestGenericService<int> IntService { get; }

    public Outer(ITestGenericService<int> intService)
    {
        IntService = intService;
    }
}

[Fact]
public void GenericFactoryIntoConstructor()
{
    var container = new DependencyInjectionContainer();

    container.Configure(c => c.AddActivationStrategy(new GenericFatoryExportStrategy(container,
        typeof(ITestGenericService<>), FactoryMethod)));
  
    var outer = container.Locate<Outer>();
    Assert.NotNull(outer);
    Assert.IsType<Outer>(outer);
    Assert.NotNull(outer.IntService);
    Assert.IsType<Impl1>(outer.IntService);
}
```

**Comment by mcdis** [comment]
Hi @ipjohnson good job.
Yes, you can close and go ahead
