### ISSUE TITLE
Differenece between Keyed and Named

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#140]
What's difference between registation AsKeyed, AsName?
How to use AsName?
At this moment I'm using only As Keyed, like:
```csharp
_this.Configure(_=>_.Export<TToolbar>().AsKeyed<IUiToolbarItem>(_toolbarId.Path));
//...
_this.Localte<IUiToolbarItem>(wthiKey:"abc");
```

**Comment by ipjohnson** [comment]
Hi @mcdis 

The big difference is that Named has no type associated with it (you look it up by name only no type), where as keyed exports by type with a key associated. 

The named methods fit a very specific niche where you are looking for something by name and don't care what type it is (MVVM framework where databind happens at runtime so you don't care what type it is).

**Comment by ipjohnson** [comment]
I'm going to close this as completed
