### ISSUE TITLE
Logging using DI

### ISSUE THREAD

**Issue by jan-schubert** [ipjohnson/Grace#141]
Hi.
Because of the great performance, we try to migrate our project from Ninject to Grace.
Now I try to configure our own ILog interface by using DI.

Ninject configuration: 
`container.Bind<ILog>().ToMethod(context => logProvider.GetLogger(context?.Request.Target?.Member.DeclaringType)).InTransientScope();`

Is it possible to get the type of the object that request ILog?

Sample:

```
DependencyInjectionContainer container = new DependencyInjectionContainer();
//????? container.Configure(c => c.ExportFunc(logProvider.GetLogger));
container.Configure(c => c.Export<BasicService>().As<IBasicService>());

public class BasicService : IBasicService
{
  private readonly ILog _log;

  public BasicService(ILog log)
  {
    _log = log;
  }

  public void Print()
  {
    _log.Debug("Basic");
  }
}

public class Log : ILog
{
  private readonly Type _requestedType;

  public Log(Type requestedType)    // <----------- should be typeof(BasicService)
  {
    _requestedType = requestedType;
  }
}
```

**Comment by ipjohnson** [comment]
Hi @jan-schubert 

You want to do something like this

``` C#
container.Configure(c => c.ExportFactory<StaticInjectionContext, ILog>(
         context => logProvider.GetLogger(context?.TargetInfo.InjectionType)));
```

**Comment by jan-schubert** [comment]
Thank you. Now I found a unit test for my case (FactorySpecialTypeTests.Factory_Depend_On_IExportLocatorScope_StaticContext).
