### ISSUE TITLE
Grace and WebAPI 2

### ISSUE THREAD

**Issue by davidkeaveny** [ipjohnson/Grace#142]
Is there any plan to out-of-the-box support WebAPI 2 and its `IDependencyResolver` interface? If not, are there any suggestions for how to imeplement the `BeginScope` method?

**Comment by ipjohnson** [comment]
hi @davidkeaveny 

Sorry for the slow reply. I don't have any plans to support anything out of the box for web api 2 at this time. That said it shouldn't be to hard to do. I'll try and put together a sample and post it.

**Comment by davidkeaveny** [comment]
I've got this working; if I were to contribute the code back to the project, what's the best way of doing it? Create a similar solution and assembly to the Grace MVC support?

**Comment by ipjohnson** [comment]
Sorry meant to reply to this earlier. If you want you can create a project like the MVC one or you can send me a sample of what you have working and I can create a project. Which ever is easier for you.

Thanks for helping out.

**Comment by ipjohnson** [comment]
I'm going to mark this as closed
