### ISSUE TITLE
Bulk registration of open generics (part 2)

### ISSUE THREAD

**Issue by davidkeaveny** [ipjohnson/Grace#153]
Continuing from https://github.com/ipjohnson/Grace/issues/148, I've got a slightly different issue; previously, I was registering all implementations of the following:

```
public interface IQueryHandler<in TQuery, out TResult> where TQuery : IQuery<TResult>
{
    TResult Handle(TQuery query);
}
```
using the following code in a configuration module:
```
configure.Export(GetType().Assembly.ExportedTypes)
    .BasedOn(typeof(IQueryHandler<,>))
    .ByInterfaces();
```
then I would resolve them thusly:
```
protected TResult Query<TQuery, TResult>(TQuery query) where TQuery : IQuery<TResult>
{
    var handler = _container.Locate<IQueryHandler<TQuery, TResult>>();
    return handler.Handle(query);
}
```
and there was much rejoicing.

Now however, I want to change my resolution of the type to be like this:
```
protected TResult Query<TResult>(IQuery<TResult> query)
{
    var handler = _container.Locate<IQueryHandler<IQuery<TResult>, TResult>>();
    return handler.Handle(query);
}
```
but I am getting a `LocateException`. I tried explicitly registering a query handler like this:
```
configure.Export<SomeConcreteQueryHandler>()
    .As<IQueryHandler<IQuery<ConcreteResult>, ConcreteResult>>();
```
but that results in a `RecursiveLocateException` instead.

So I don't know if the problem is how I am registering my types, or how I am resolving them! Any ideas?

**Comment by ipjohnson** [comment]
@davidkeaveny that's a very interesting problem I would have assumed they all work but generics can be tricky. I'm heading out on vacation tomorrow so I don't think I'll have time to look at this till next week. 

Would it be possible to put together a simple solution showing this and send it along?

**Comment by davidkeaveny** [comment]
Repro attached: [Cqrs.zip](https://github.com/ipjohnson/Grace/files/1835657/Cqrs.zip)

I tried replacing Grace with StructureMap and got something similar, although SM gave me a compile-time error when I tried to explicitly register the type.

**Comment by davidkeaveny** [comment]
Looks like you're right; in the end, I took the approach used by Mediator, which has a wrapper which is able to make the necessary conversion from `IQueryHandler<TestQuery, TestModel>`  to `IQueryHandler<IQuery<TestModel>, TestModel>`.
