### ISSUE TITLE
ExportPriority Attribute not used

### ISSUE THREAD

**Issue by mgth** [ipjohnson/Grace#178]
I used ExportPriority Attribut but after ExportAssembly all exports still have a priority of 0.

**Comment by ipjohnson** [comment]
Hmmm try adding `.ExportAttributedTypes()` to the call as by default grace won't process attributes on a type. 

If it's still and issue I can take a look this evening.

**Comment by ipjohnson** [comment]
@mgth did that work for you?

**Comment by mgth** [comment]
Sorry for the loonng delay.
I ended up by sorting the export order and woks ok for me.
I already used ExportAttributedTypes(), but exports in the container are all zero priority.

**Comment by ipjohnson** [comment]
cool. I'm going to go ahead and close this
