### ISSUE TITLE
Add ExportAsKeyed extension

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#193]
We are already have **ExportAs** extension.
Add **ExportAsKeyed** extension:
`static IFluentExportStrategyResgistration<TImpl> ExportAsKeyed<TImpl,T>(this IExportRegistrationBlock _this, object key);`
shorten equalent of 
`Export<TImpl>().AsKeyed<T>(key);`

**Comment by ipjohnson** [comment]
Hi @mcdis

I think I can add that, I’ll try and find some time in the coming week to add it and do a beta.

**Comment by ipjohnson** [comment]
@mcdis, I pushed out a beta with this change

**Comment by ipjohnson** [comment]
closing as released in 6.4.2
