### ISSUE TITLE
Q: What are advantages of Deferred Lifestyle?

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#196]

**Comment by ipjohnson** [comment]
Hi @mcdis 

The deferred singleton lifestyle is only useful when you're having issues with circular dependencies. Essentially when using the normal singleton lifestyle the instance is created during the construction of the compiled linq expression for maximum performance. The deferred singleton doesn't construct the instance until the very end after the linq expression has been constructed and compiled. It sacrifices a very small amount of performance for the ability to be constructed later in the resolution process.

I've only seen one or two situations where the deferred lifestyle was needed.

**Comment by dadhi** [comment]
@mcdis Sorry for intruding. I would imagine the case, when the whole graph is failing for some reason, without deferred lifestyle you may still get singletons created. Which maybe not what you'd expect.

**Comment by ipjohnson** [comment]
@dadhi touches on an interesting side affect because the Singleton is created during the expression creation it can have an interesting side effect in case of failure or even trying to understand the order of creation.

**Comment by ipjohnson** [comment]
@mcdis can I close this out?
