### ISSUE TITLE
Safe property injection (auto readonly) before constuctor called

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#198]
Hi!
I suggest to make that scenario:
Inject auto prop get only before constructor called. 
I didn't look in deep in code, but if you use create uninitialized object then you can inject properties before constructor and make prop injection in safe way.
Sometime It's not friendly to drag all dependencies over constructor...for example when I've some hierarchy

**Comment by ipjohnson** [comment]
Hi @mcdis 

I've added an example of how you could auto inject auto properties, but they are injected after the constructor is called. Grace uses linq expressions to build object graphs and there isn't really a new but uninitialized.
