### ISSUE TITLE
Method not found in Grace.Net

### ISSUE THREAD

**Issue by silkfire** [ipjohnson/Grace#203]
@ipjohnson I've downloaded the Grace.Net package as I wanted to use the `Types.FromThisAssembly()` method, but it throws an exception:

![image](https://user-images.githubusercontent.com/1554615/52477868-bbaf4400-2ba3-11e9-959c-93aac3b05e4d.png)

Could this have to do with that the package is incompatible with .NET Core?

**Comment by SuperJMN** [comment]
It's not there. It's probably removed or renamed.

@ipjohnson BTW, I wrote you a e-mail message. Is your old Yahoo account alive? :)

**Comment by ipjohnson** [comment]
Hi guys, Grace.Net was there just to do some assembly scanning for .net. When I re-wrote Grace for .net standard it some of the features weren't supported so I didn't continue to develop it. 

Now that .net standard 2.0 support the features it was missing I could bring it back but there really wasn't much there other than scanning the currently loaded assemblies for exports.

@SuperJMN my email is still the same and I replied to say hi :)

**Comment by sgf** [comment]
> Hi guys, Grace.Net was there just to do some assembly scanning for .net. When I re-wrote Grace for .net standard it some of the features weren't supported so I didn't continue to develop it.
> 
> Now that .net standard 2.0 support the features it was missing I could bring it back but there really wasn't much there other than scanning the currently loaded assemblies for exports.
> 
> @SuperJMN my email is still the same and I replied to say hi :)


Just Update the Docoment https://github.com/ipjohnson/Grace/wiki/Fluent-Configuration
and tell us witch the lastest way how to Bulk/Batch Register types

**Comment by ipjohnson** [comment]
Will do

**Comment by moalamri** [comment]
Types can be replaced with `Assembly.GetExecutingAssembly().GetTypes()`
