### ISSUE TITLE
Logo for the library

### ISSUE THREAD

**Issue by silkfire** [ipjohnson/Grace#217]
Have you considered to add a logo to your library? If you want, I can come up with a few design ideas. Something that would aptly fit the name, of course :)

**Comment by ipjohnson** [comment]
I actually hadn’t, I’d definitely be interested in seeing your designs.

**Comment by silkfire** [comment]
Great, I'll come back to you in a few days with my suggestions. Any preference when it comes to colors, shapes or imagery to be used?

**Comment by ipjohnson** [comment]
Thanks that would be really cool. Maybe greens or blues?

**Comment by silkfire** [comment]
Here's a couple of designs I made in Illustrator. What do you think?

![grace-1](https://user-images.githubusercontent.com/1554615/56696243-8f5b8c00-66eb-11e9-8208-27f963fc4b36.png)
![grace-2](https://user-images.githubusercontent.com/1554615/56696244-8f5b8c00-66eb-11e9-80a6-295f74e33d22.png)
![grace-3](https://user-images.githubusercontent.com/1554615/56696245-8f5b8c00-66eb-11e9-95b1-d29fad8484c8.png)

**Comment by ipjohnson** [comment]
Those look nice, I think I'll go with the bottom one and see if I can get it in for the 7.0 release

**Comment by silkfire** [comment]
Wooooow, glad you found one you liked. Looking forward to seeing it live.

Would you like me to make a PR where I include it in an `/img/` folder? I assume you know how to refer to it from the `.nuspec`?

**Comment by ipjohnson** [comment]
Sure a PR would be great, could you possible do a couple size 256,128,64?

**Comment by silkfire** [comment]
See pull request at https://github.com/ipjohnson/Grace/pull/219

**Comment by ipjohnson** [comment]
Awesome, thanks!

**Comment by ipjohnson** [comment]
Looks great. I'm going to get it added into the other satellite packages and should be ready for release.

Thanks again!

**Comment by silkfire** [comment]
@ipjohnson My pleasure. This should give the package a bit of character :)

Btw, please make sure to edit the link to the SVG icon in the README.MD from:

`https://raw.githubusercontent.com/silkfire/Grace/e0415b74141fbc17c88cbec7dd978460b3c9300a/img/logo.svg?sanitize=true`

to

`https://raw.githubusercontent.com/ipjohnson/Grace/7c24bfa184bc4b984e64b9e8d2457200a64a0724/img/logo.svg?sanitize=true`

As it was pointing to the image relative to my fork.
