### ISSUE TITLE
MetadataAttribute can't be comined

### ISSUE THREAD

**Issue by ipjohnson** [ipjohnson/Grace#218]
@SuperJMN brought to my attention that the MetadataAttribute doesn't allow multiple to be applied. This is just a matter of adding a UsageAttribute to the MetadataAttribute class.

**Comment by ipjohnson** [comment]
This has been implemented and will be in 7.0

**Comment by SuperJMN** [comment]
WONDERFUL! Thank you a lot!

**Comment by SuperJMN** [comment]
I've seen that there are some pre-7.0 packages out there. Is 7.0 close to its release?

**Comment by ipjohnson** [comment]
Probably a week or two. There is a nightly nuget feed if you want to try it out. 

https://ci.appveyor.com/nuget/grace-master

**Comment by SuperJMN** [comment]
I'm on a trip until Monday, but after that, I'm definitely into it. And playing with EasyRpc.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
