### ISSUE TITLE
Question:  How do I get IInjectionScope inside a Builder

### ISSUE THREAD

**Issue by scovel** [ipjohnson/Grace#224]
Is it possible to use the Grace IInjectionScope inside the chain of builder methods?  I see IServicesCollection, but I need to do some fancy keyed injection and whatnot.

```
IWebHost server =  builder.UseGrace() // add grace container
.DoSomethingThatUsesIInjectionScope()
.UseStartup<StartupStub>()
.UseKestrel()
.Build();
```

**Comment by silkfire** [comment]
@scovel  I think you can use the `IWebHostBuilder.Configure` method in your building pipeline, but unfortunately it will replace your `Startup.Configure(IApplicationBuilder app, IHostingEnvironment env)` method as well:

```
builder.UseGrace()
       .Configure(app =>
       {
           var requiredService = app.ApplicationServices.GetService<IRequiredService>();
       })
       .UseStartup<StartupStub>()
       .UseKestrel()
       .Build();
```

**Comment by ipjohnson** [comment]
@scovel I'm actually not sure you can as I'm not positive where in the asp.net core pipeline the DependencyInjectionContainer is created. The UseGrace method essentially tells the framework that Grace should be used for IServiceProvider but when and where the container is created is controlled by asp.net core. 

Are you looking to do registrations or some type of resolution?

**Comment by scovel** [comment]
I'm trying to do some registrations.  I wanted to be able to conditionally add different services, and some of them using keyed injection.  It is possible to get IServiceCollection, but that only lets you do very basic registrations.  Seems like service location isn't possible until the IServiceCollection is made into an IServiceProvider.

Seem like after Build is called, the resulting IWebHost does have access to a ServiceProvider.

var myService = webHost.Services.GetService<MyService>();

Maybe I need to find a different way...

**Comment by ipjohnson** [comment]
You can do ContainerConfigure method to your startup to do more advanced configuration.

```
        public void ConfigureContainer(IInjectionScope scope)
        {
            // custom registration
        }
```

Actually doing registration from a WebHostBuilder extension is harder and would require creating a custom implementation of UseGrace (not hard just custom).

**Comment by ipjohnson** [comment]
@scovel were you able to find a solution to your problem?

**Comment by scovel** [comment]
Yeah, I'm restructuring how I load stuff at start-up.  Thanks for checking in on me.
