### ISSUE TITLE
Migrate 7.0 help

### ISSUE THREAD

**Issue by mcdis** [ipjohnson/Grace#239]
Dear Yan,
my respect to you, you do a great job!

I want to migrate from 6.4.2 -> 7.0 and before I do that I decided to do some research.
I am worried about breaking changes #208 #209.
Can you provide any tiny example that demonstrate what works in 6.4.2 and doesn't work in 7.0?

Best regards,  Alexander

**Comment by ipjohnson** [comment]
Sorry I meant to reply to this earlier. Those two issues really only apply if you were doing MVC with custom disposal code. 

What platform are you on?

**Comment by mcdis** [comment]
Hi!

> Those two issues really only apply if you were doing MVC with custom disposal code.

That's enough to start migration (for me).
