### ISSUE TITLE
Locate method using open generics doesn't use extraData

### ISSUE THREAD

**Issue by SuperJMN** [ipjohnson/Grace#246]
Given this piece of code:

```
void Main()
{
	var container = new DependencyInjectionContainer();
	container.Configure(x =>
		{
			x.Export(typeof(MyClass<>)).Lifestyle.Singleton();
			x.Export<SomeService>().Lifestyle.Singleton();
		});
		
	Expression<Func<int, int>> data = x => x; 
	var myInstance = container.Locate<MyClass<int>>(extraData: data);
}

class MyClass<T> 
{
	public MyClass(SomeService service, Expression<Func<T, int>> expression)
	{		
	}	
}

class SomeService 
{	
}
```

# Expected result
I would like the container to use the extra data I'm providing, but it seems it's trying to locate it instead.

# Actual result
An exception is thrown

# Important note
If you remove the registration the line that says 			`x.Export(typeof(MyClass<>)).Lifestyle.Singleton();`, it works, but then I cannot configure the lifestyle.

**Comment by SuperJMN** [comment]
I've tried to workaround the issue with this code, but it still fails

```
void Main()
{
	var container = new DependencyInjectionContainer();
	container.Configure(x =>
		{
			x.ExcludeTypeFromAutoRegistration(typeof(Filter<>));
			x.Export(typeof(MyClass<>)).Lifestyle.Singleton();
			x.Export<SomeService>().Lifestyle.Singleton();
		});

	var filter = new Filter<int>(x => x);
	var myInstance = container.Locate<MyClass<int>>(extraData: filter);
}

class MyClass<T>
{
	public MyClass(SomeService service, Expression<Func<T, int>> expression)
	{
	}
}

class SomeService
{
}

public class Filter<T>
{
	public Expression<Func<T, int>> Expression { get; }

	public Filter(Expression<Func<T, int>> selector)
	{
		Expression = selector;
	}
}
```

**Comment by ipjohnson** [comment]
Hi @SuperJMN 

The reason this isn't working is because Singleton lifestyle can't received extra data. The reason being that you create a scenario where the singleton can be created differently depending on the order of the resolution. It creates odd bugs that are hard to find. 

I can put together a custom lifestyle for you but I can't change the default behavior as it would be a major breaking change.

**Comment by SuperJMN** [comment]
Hi @ipjohnson!

The problem I have with my scenario is that I want to share the same instance around the application. 

The real use case is that I have a lot of child ViewModels **A** with share another ViewModel **B**. The contents of **B** are potentially immutable (that's why I'm making it a singleton). The problem is that **B** is generic and it get an Expression to do its job, that is provided using the extra data feature.

I'm not sure if there's an easy path for this. I'm looking into changing my class design to something easier.

Thanks for your help and your patience!

**Comment by SuperJMN** [comment]
The solution has been to use a DeferredSingletonLifestyle!

It seems that the default Singleton lifestyle doesn't use the **extra data**, and this behavior is the expected!

To summarize, I'll try to explain my use case better. I wanted the following:
- To provide an `Expression<Func<T, int>>` via constructor.
- `MyClass<A>` and  `MyClass<B>` should be constructed with different expressions, `Expression<Func<A, int>>` and `Expression<Func<B, int>>`.
- These given expressions won't change. So, `MyClass<A>` will always hold the same instance of `Expression<Func<A, int>>`

Thanks for your help, as always, Ian! Without it, I wouldn't have solved it.
