### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eglauko** [ipjohnson/Grace#252]
Using IServiceCollection i get a service registered as a singleton instance as follows:
```
            var descriptionCollection = services
                .Where(s => s.ServiceType == typeof(MessageDescriptorCollection))
                .Select(s => (MessageDescriptorCollection)s.ImplementationInstance)
                .FirstOrDefault();
```
If the returned value is null, I create a new instance and register it in the collection.
Then I use this instance in a builder.

How can I do the same thing using Grace's container?
The only thing I can do is check if the service is registered:
```
            bool exported = false;
            container.Configure(c => exported = c.IsExported(serviceType));
```

**Comment by ipjohnson** [comment]
hmmm at this moment there isn’t anything you can look at but I think it’s do able. I’ll probably have some time this weekend to look at adding support for something like that.

**Comment by ipjohnson** [comment]
So I took a look this weekend and it's going to be hard to provide a list of current exports from the current `Configure` call. All previous calls that have completed will be listed in the `container.StrategyCollectionContainer` and you can inspect all registered exports.

**Comment by eglauko** [comment]
I'm going to take a look.

**Comment by ipjohnson** [comment]
Were you able to find the strategy you were looking for?

**Comment by eglauko** [comment]
The strategy I found, but I don't know how to get the instance from it.

```
            var container = new DependencyInjectionContainer(GraceDynamicMethod.Configuration());

            container.Configure(c =>
            {
                c.ExportInstance(new MyInstanceObject());
                c.Export<AlphaNameService>().As<INameService>();
            });

            var serviceType = typeof(MyInstanceObject);

            var strategy = container.StrategyCollectionContainer
                .GetActivationStrategyCollection(serviceType)
                ?.GetPrimary();
```

**Comment by ipjohnson** [comment]
I would normally write a unit test as an example but today I'm strapped for time so you'll have to forgive me is this isn't 100% spot on.

```
var invokeDelegate = strategy.GetActivationStrategyDelegate(container, ((IInjectionScope)container).StrategyCompiler, typeof(MyInstanceObject));

var instance = invokeDelegate(container, container, null);
```

All that said is your whole goal only to register something if it doesn't already exist or are you looking to see what the actual implementation is?

**Comment by eglauko** [comment]
Well, I can handle it this way here. 
It's not exactly like what I do with IServiceCollection, but it will work.
```
MessageDescriptorCollection descriptors;

var strategy = container.StrategyCollectionContainer
    .GetActivationStrategyCollection(typeof(MessageDescriptorCollection))
    ?.GetPrimary();

if (strategy == null)
{
    descriptors = CreateMessageDescriptorCollection();
    container.Configure(c =>
    {
        c.ExportInstance(descriptors);
    });
}
else
{
    descriptors = container.Locate<MessageDescriptorCollection>();
}
```

**Comment by ipjohnson** [comment]
Check out the `IfNotRegistered` method in these [tests](https://github.com/ipjohnson/Grace/blob/master/tests/Grace.Tests/DependencyInjection/Registration/OnlyIfExportTests.cs). It might help for your situation

**Comment by ipjohnson** [comment]
What did you end up with for a solution?

**Comment by eglauko** [comment]
I found a solution similar to the last comment.
Thanks for your attention and help.
