### ISSUE TITLE
Keyed resolution over-rides Non-keyed.

### ISSUE THREAD

**Issue by prasannavl** [ipjohnson/Grace#26]
class Program
    {
        private static int _i;

        public static int i
        {
            get { 
                _i++; return _i;
            }
            set { _i = value; }
        }

        static void Main(string[] args)
        {
            var c = new DependencyInjectionContainer();
            c.Configure(x =>
            {
                x.ExportInstance<string>((s, cx) => "Hello");
                x.ExportInstance<string>((s, cx) => "Hello" + i.ToString()).AsKeyed<string,string>("h2").Lifestyle.SingletonPerScope();

            });

            var sc = c.BeginLifetimeScope();

            Console.WriteLine(sc.Locate<string>());
            Console.WriteLine(sc.Locate<string>(withKey: "h2"));

            Console.WriteLine("Done");
            Console.ReadLine();
        }

    }

I would expect the result to be Hello and Hello1.

But it seems the result is simple Hello1 and Hello1. The first registration is over-riden by the keyed registration. This behavior seems odd if it was by design, or else a bug.

**Comment by ipjohnson** [comment]
I've just released version 3.0.0 and this is included.
