### ISSUE TITLE
IExportPriorityAttribute is unused

### ISSUE THREAD

**Issue by jods4** [ipjohnson/Grace#262]
I'm trying to set priority on an export using attributes.
(it's a custom attribute implementing `IExportPriorityAttribute`).

It doesn't work and when I look at the strategies, I notice the `Priority` is still 0.

I searched the sources for `ProvidePriority` but it looks like it's never called?

**Comment by ipjohnson** [comment]
Ok I've added the code to process the attribute. I'm around today and all weekend if you run into anything else ping me and I can address it.

**Comment by jods4** [comment]
Thank you, that was really fast!
I wouldn't dare ask for an answer over the week-end. Your support goes way beyond expectations, it's much appreciated.  ❤️ 

Grace is a fantastic IOC: it's fast, it has many advanced features and the support is top notch.

It breaks my heart when I read articles about .net DI and see pretty much every container listed _but Grace_.

I don't know if you'd want more recognition/users (because it also means more work and toxic requests, right?) but if you do I think there's two things Grace needs:
1. A good looking website with good docs (docs is the one thing I think Grace could do better at);
2. A little push from someone with many followers (easy enough, just ask the Gu I'm sure he'd do a post about Grace).

Have a nice week-end!

**Comment by silkfire** [comment]
@jods4 I agree with everything you say. Grace is hands down the best DI (and probably the most underrated) out there with the support from its humble creator being one of its best feature (yea I'd go so far to say that it is a feature). As an aside, I know that Grace was actually mentioned in a post about NServiceBus along with other popular DI container libraries:

https://particular.net/blog/nservicebus-now-supports-microsoft-extensions-dependencyinjection

**Comment by ipjohnson** [comment]
Thanks for the kind words. The people I've interacted with over the years have been great, I'm just a little short on time currently as I have one project I need to finish up before I can get back to Grace. I think once fall comes I can get a little more time to put towards document, a nice site and some good docs would go along way to helping ease the learning curve.

**Comment by jods4** [comment]
@ipjohnson May I ask if you have an ETA for a release of this fix on Nuget?
On my machine I can direct to alternative (nightly) feeds but I can't do that in our CI.
Thanks!

**Comment by ipjohnson** [comment]
Sorry forgot this was pending. I just pushed this to nuget

**Comment by jods4** [comment]
Awesome, thanks!
