### ISSUE TITLE
GetMemeberType spelling mistake

### ISSUE THREAD

**Issue by daveraine** [ipjohnson/Grace#266]
https://github.com/ipjohnson/Grace/blob/83840b915537c1bf11e86c1a6dbc15d96184df55/src/Grace/Utilities/ReflectionHelper.cs#L129

I just noticed a spelling mistake while using this library. This should be `GetMemberType`.

**Comment by ipjohnson** [comment]
Thanks I'll put in a fix and mark this method as obsolete.

**Comment by ipjohnson** [comment]
This has been implemented
