### ISSUE TITLE
Cannot resolve one dependency by open generic type

### ISSUE THREAD

**Issue by davidkeaveny** [ipjohnson/Grace#269]
Hi there,

I'm using Grace 7.1.1 with an ASP.NET Core 3.1 Web API, and am having a very weird problem with one specific dependency resolution that I hope someone can help with.

The API is resolving the following dependency:

```
public class AuthenticationQueryHandler : IQueryHandler<AuthenticationQuery, AuthenticationResult>
{
  private readonly ILoginService _logins;

  public AuthenticationQueryHandler(ILoginService logins) {
    _logins = logins;
  }

  public AuthenticationResult Handle(AuthenticationQuery query) {
    return _logins.Authenticate(query.Username, query.Password);
  }
}
```

The registrations are as follows:
```
var assemblies = Directory
  .GetFiles(AppDomain.CurrentDomain.BaseDirectory, "MyProject.*.dll")
  .Select(Assembly.LoadFile)
  .ToList();
register.ExportAssemblies(assemblies).BasedOn(typeof(IQueryHandler<,>)).ByInterfaces();

register.Export<LoginService>().As<ILoginService>();
```

When I try to resolve the `AuthenticationQueryHandler` using `IQueryHandler<AuthenticationQuery, AuthenticationResult>` then I get a `LocateException` on the `logins` parameter, saying that the `ILoginService` cannot be located. If I try to resolve the `AuthenticationQueryHandler` using `AuthenticationQueryHandler` then it resolves correctly. If I try to resolve `ILoginService` then it also resolves correctly, although it is also listed in the `PossibleMissingDependencies`.

Other implementations of `IQueryHandler<,>` resolve fine, so the registration process seems to be working okay.

**Comment by davidkeaveny** [comment]
I also just found that if I replaced the `ILoginService` dependency with an `IServiceProvider` then called `(ILoginService)serviceProvider.GetService(typeof(ILoginService))` in my `AuthenticationQueryHandler` then the dependency would also be resolved correctly, which I guess is a sort of work-around, but it's a bit of an anti-pattern.

**Comment by ipjohnson** [comment]
Hi @davidkeaveny 

That doesn't make much sense to me, I also agree passing in the `IServiceProvider` is not a good solution. Can you run call what do I have on the container after you've finished registering to see what's exported in the container?

**Comment by ipjohnson** [comment]
Where did you end up on this?

**Comment by davidkeaveny** [comment]
Sorry, I ended up switching to Autofac for this one, I was on a tight deadline.

**Comment by ipjohnson** [comment]
I’m going to close this out without a project to reproduce it
