### ISSUE TITLE
A way to find out if a singleton was resolved

### ISSUE THREAD

**Issue by prasannavl** [ipjohnson/Grace#27]
Hi, I was wondering if there was anyway to figure out if a registered singleton was resolved (thereby already created) without using `Locate<TheSingleton>`, since that would create it if it doesn't exist already. 

My scenario is that, I'm trying to update the a few services in runtime. So, I have to update the services that already may have been resolved, which would have it as a dependency. But I'd rather not resolve a singleton if it already wasn't resolved, until they are needed. Could you please suggest the best way forward?

Thanks. 

Edit: Also, is there anyway to re-resolve a singleton, without resorting to never resolving directly and using a Func?

As I see, I can understand, the container really just has IStrategies that can be removed, and modified cleanly, but I fail to understand how singletons are handled, and where they are cached.

**Comment by prasannavl** [comment]
Also, is there anyway to re-resolve a singleton, without resorting to never resolving directly and using a Func?

**Comment by prasannavl** [comment]
Alright, just went through the source. As I understand it, they are in the stored in the corresponding ILifetime. I suppose simply re-configuring should do the trick?

**Comment by ipjohnson** [comment]
Hi Prasanna,

I'll write up a more detailed reply this evening but quickly to answer your question yes all the logic is in the ILifestyle interface. Also check out the GetStrategy method it will locate an export without instantiating it.

-Ian

**Comment by ipjohnson** [comment]
So to answer your question a little more in depth the GetStrategy method returns an IExportStrategy. The Lifestyle property will contain an ILifestyle that controls how instances are created & returned. 

Currently there isn't any way to tell if an instance has been created or to clear an instances that exists. This has been asked for a couple time so I think I'll implement something like 

public interface ISingletonLifestyle : ILifestyle
{
  bool HasInstance { get; }

  void Release(bool callDispose = true);
}

Would that be useful for you?

**Comment by prasannavl** [comment]
Thank you Ian. 

This has been very helpful. And yes, I think a HasInstance property that returns the result of the null check should be perfect. But I wonder, instead of having a release, is there any particular reason why the Lifestyle property doesn't have a setter in IExportStrategy? From my (non-thorough) glance, I realized, the lifestyle property does go through rigorous checks where ever it is used in your implementations. 

Perhaps by making it a setter, you can in turn, change the ILifestyles into a more immutable state? So, a dispose, and a simple clone on the lifestyle, instead of Release. As an added advantage, lifestyles can be dynamically changed. 

I haven't gone through the entire code, so its highly possibly there is a reason why it has no setter, or perhaps it doesn't just because it wasn't needed. Thoughts?

**Comment by ipjohnson** [comment]
I think it's less of a technical reason and more of a philosophical. The over whelming common use case is to maintain the same lifestyle through the life time of the container. Giving an easy way to change the lifestyle implies similar behavior for all lifestyles (that they can be disposed and swapped). This works well for singleton lifestyles but not nearly as well for other lifestyles like pooled. 

That said if you can cast it to an IConfigurableExportStrategy and do what you are looking to do if you wanted to swap strategies. Though I'd recommend creating your own custom ILifestyle before that as it's a little nicer and cleaner.

I look at IExportStrategy and ILifestyle as very very generic capable of representing most any idea while enforcing as little behavior as possible. With the intention that if you are look for more specific behavior you can cast the instance to different export type or lifestyles (ie. IConfigurableExportStrategy, ISingletonLifestyle, etc).

**Comment by prasannavl** [comment]
Makes sense. I didn't realize it has a configurable type in its inheritance tree. Yes, creating a custom lifestyle seems to be a cleaner way. But for quick hacks, casting covers. This is very neat! 

Graceful, indeed. :)

**Comment by ipjohnson** [comment]
Thanks, it's one of those features I don't advertise mainly because it's getting more into the guts of the container. Very useful but something most people don't need and is more of an advanced topic.

**Comment by ipjohnson** [comment]
I'm going to mark this as closed
