### ISSUE TITLE
Visual Studio Templates link is broken

### ISSUE THREAD

**Issue by breyed** [ipjohnson/Grace#29]
The Visual Studio Templates link in the README is broken. To repro, follow the link in a private browsing session.

**Comment by ipjohnson** [comment]
Hi Breyed,

I think moving forward I'm going to drop support for custom templates. Templates that were there were for MVC 4 and trying to keep pace with Microsoft and all their templates is really a futile effort.

Out of curiosity was there a particular type of project you were looking for?

**Comment by ipjohnson** [comment]
For some reason MS decided to lock out the templates. Not really sure why. I'll update this item when I learn more. For the moment I'll remove it from the readme

**Comment by ipjohnson** [comment]
Marking as closed.
