### ISSUE TITLE
How do you use Grace with the .Net 6.0 "minimal api"

### ISSUE THREAD

**Issue by scovel** [ipjohnson/Grace#290]
Love you lib, been using it for years.

I'm trying to figure out how to use Grace with the new "minimal api" templates for .Net 6.0.  I'd call it "Startup-less", since there is no magic Startup.cs class.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0

Specifically, in my old Startup.cs I had the following magic:

```
   public virtual void ConfigureContainer(IInjectionScope scope)
   {
        scope.Configure(c =>
        {
             c.Export<UserResolver>().As<IUserResolver>().Lifestyle.Singleton();
             c.Export<HttpHeaderResolver>().As<IHttpHeaderResolver>();
             c.Export<Profile>().As<IProfile>();
        }
   }
```

In the above article, to access the built-in DI container, you do the following:

```
var app = builder.Build();

app.MapControllers();

using (var scope = app.Services.CreateScope())
{
    var sampleService = scope.ServiceProvider.GetRequiredService<SampleService>();
    sampleService.DoSomething();
}
```

How do you accomplish the same with Grace?

Thanks!

**Comment by silkfire** [comment]
There's been support added for this to Grace recently:

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseServiceProviderFactory(new GraceServiceProviderFactory());

builder.Host.ConfigureContainer<DependencyInjectionContainer>(c=> c.Configure(...));

var app = builder.Build();
```

**Comment by scovel** [comment]
Thanks for the quick response.  Another reason I like Grace.  Your support is excellent.

Is this in the Beta?  I don't see it in 7.2.1, I'm not seeing it in 8.0.0-beta132.

```
builder.Host.UseServiceProviderFactory(new GraceServiceProviderFactory());

  Program.cs(17, 44): [CS7036] There is no argument given that corresponds to the required formal parameter 'configuration' of 'GraceServiceProviderFactory.GraceServiceProviderFactory(IInjectionScopeConfiguration)'
```
Am I missing an import or something?

Thanks

**Comment by silkfire** [comment]
Yep it should be in [8.0.0-beta132](https://www.nuget.org/packages/Grace.AspNetCore.Hosting/8.0.0-beta132), but I haven't tried it out myself.

I may have messed up the syntax. Try this instead:

`builder.Host.ConfigureContainer<DependencyInjectionContainer>((_, c) => c.Configure(...));`

**Comment by scovel** [comment]
Yes, I was doing .UseGrace, but needed to know how to get direct access to the container in the main() as opposed to the Startup.cs.  It seems like your new syntax compiles.  I need to throw a little more code together to make sure it's all working.

```
builder.Host.ConfigureContainer<DependencyInjectionContainer>((_, c) =>
{
    c.Configure(block =>
    {
        // register all [Tracing] attributes for Interception
        block.OwningScope.InterceptAttribute<TracingAttribute, TracingInterceptionHandler>();
    });
});
```

Does this look correct?

**Comment by ipjohnson** [comment]
@scovel did @silkfire suggestion work for you?
