### ISSUE TITLE
Compatibility with .NET Core

### ISSUE THREAD

**Issue by kennedyjd** [ipjohnson/Grace#40]
Hey Ian,

As .NET Core 1.0 has been released (see http://www.theregister.co.uk/2016/06/28/microsoft_releases_crossplatform_net_core_10_at_linux_event/), how about upgrading to support it?

I did the port myself and it only took a couple of hours.  I've asked our lawyer folks if I can send a .zip of what I did to you (which does not incorporate your latest) and am waiting on their response.

FWIW, project.json is a bit of a pain (see: https://www.infoq.com/news/2016/05/project-json/).  That said, you'll have to deal with it for now as there is no other way yet to do the cross platform stuff.

Thoughts?

-- Joe

**Comment by ipjohnson** [comment]
Hi Joe,

I've released a ASP.Net Core adapter [Here](https://github.com/ipjohnson/Grace.DependencyInjection.Extensions) and a companion library [Here](https://www.nuget.org/packages/Grace.AspNetCore.MVC/) that provides a controller activator and view activator (as well as supports [FromQuery] attributes for all DI). I'm using just starting a new ASP.Net core project at work so better support is on my radar.

That said I do want to convert the project over to netstandard1.2 as well as C# 6 in the coming weeks. If the lawyers give the thumbs up I'd definitely like to take a look.

If there is something specific that isn't supported or not working let me know but I think (fingers crossed) the fact grace is a PCL it should work on all of the platforms (including linux & mac).

-Ian

**Comment by kennedyjd** [comment]
Hey Ian,

As memory serves, everything went over pretty easily (there was a little changing due to changes in the .NET APIs), but nothing terribly dramatic.

Either way, I'm happy to lend a hand if needed / desired.  I'll let you know next week what they say.

Cheers,

-- Joe

**Comment by ipjohnson** [comment]
Sounds good, at the moment I'm merging in the 4.0 branch and I'll create a 5.0 branch to begin the work.

**Comment by ipjohnson** [comment]
After doing a little research changing to be a .netstandard library has some bigger implications than I first realized. Mainly that PCL libraries can't reference .netstandard libraries. As Grace is a DI container it's probably not referenced directly by these libraries it's still a breaking change.

With that in mind I think I'm going to make a 4.0 branch and make the mainline be the future development with the intention of keeping the 4.0 line and do needed fixes (no new features) if someone requests it. 

I'm going to switch over my other project SimpleFixture to work the kinks out of the build/deployment process and then I'm going to switch Grace (really more just build changes than anything else, should be done end of next week).

**Comment by ipjohnson** [comment]
Hi Joe, 

I've released a beta version of Grace 5.0. It's a ground up re-write so some features haven't been included (runtime support for conditions) but I'm willing to bring back most everything if people are using it or have real use cases. The code is located in the 5.0 branch and builds are going on appveyor.

Out of the box it targets .Net 4.5, .Net Standard 1.0 and PCL Profile 259.

New Features:
* Custom Decorators - register classes to be used as decorators
* Custom Wrappers - register classes to be used as wrappers (implemented the same as `Func<>` and `Lazy<>`
* ExportFactory - export methods that take dependency and creates an export
* Custom `IEnumerable<>` - customize logic for creating enumerable (default is just array)

Performance is 6-15x faster than Grace 4.0 and slightly faster than the fastest containers available (DryIoC and LightInject).

I know it's taken me nearly 6 months to rewrite but I'm very pleased with the results and hopefully it's worth the wait.

-Ian

**Comment by ipjohnson** [comment]
This has been released as part of 5.0
