### ISSUE TITLE
Strong name signing assemblies?

### ISSUE THREAD

**Issue by RandomEngy** [ipjohnson/Grace#70]
We want our project to output strong named assemblies, but to do that all our references need to be strong-named as well. Can you strong-name sign the Grace assemblies? [The documentation](https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx) says you could even check in the private key in source control if you wanted.

**Comment by ipjohnson** [comment]
Hi Random

After reading up a little bit I think it should be pretty easy for me to sign it and get it into the build. I'll make the change in the next day or two and push a Beta build (probably 5.2.0-Beta*) to nuget for some testing. 

-Ian

**Comment by RandomEngy** [comment]
Thanks!

**Comment by ipjohnson** [comment]
Ok so I've signed Grace and all the Grace.* assemblies and pushed beta versions to nuget (5.2.0-Beta*).

Give it a whirl and let me know. I'll probably look to do a release in the next week.

**Comment by RandomEngy** [comment]
Works great, thanks!

**Comment by ipjohnson** [comment]
I've released version 6.0.0 that's signed (decided it made sense to up major version).
