### ISSUE TITLE
Add Name support

### ISSUE THREAD

**Issue by ipjohnson** [ipjohnson/Grace#71]
In previous versions there was an option to export and locate by name. I have a use case where this would be useful in a MVVM framework.

**Comment by dadhi** [comment]
Welcome to cross-cutting complexity :-)

**Comment by ipjohnson** [comment]
As Grace came from my MVVM framework and always supported this feature it's not so much "Welcome to cross-cutting complexity" as much as bringing back a feature that was left out for 5.0.

**Comment by ipjohnson** [comment]
@dadhi while you are right here I'll ask you an opinion question. I'm going to beginning signing Grace so the reference would change. For semantic versioning purposes am I ok to go from 5.1 -> 5.2 or does it need to roll to 6.0?

**Comment by dadhi** [comment]
Shaky topic. But why did you consider to sign? You may provide snk file and there are tools like [StrongNamer](https://github.com/dsplaisted/strongnamer) here.

**Comment by ipjohnson** [comment]
I had a request for it and after looking at what MS is doing with their open source projects and Autofac is doing it seems like there is no harm in signing it. Combine that with how easy it was to just put the snk file in and sign I figured it was a worth while change.

**Comment by ipjohnson** [comment]
This is implemented in versin 6.0.0
