### ISSUE TITLE
Feature Request for Fluent Interface

### ISSUE THREAD

**Issue by kennedyjd** [ipjohnson/Grace#8]
At present the fluent interfaces do not allow for custom export strategies.  It is hard coded for using either GenericExportStrategy (when  type.GetTypeInfo().IsGenericTypeDefinition) else CompiledInstanceExportStrategy.

It would be very handy to allow external definition of what strategy / ies to be used.

Cheers,

-- Joe

**Comment by ipjohnson** [comment]
This has been completed and will be released as part of 4.0
