### ISSUE TITLE
Resolve request interceptor (smth like  UnityContainerExtension / BuilderStrategy in Unity)

### ISSUE THREAD

**Issue by ILAgent** [ipjohnson/Grace#82]
It is necessary for me to have availability of service resolving interception. Sorry, if it already is, please show how to achieve. Thank you !

**Comment by ipjohnson** [comment]
@ILAgent I'm not familiar with unity's BuilderStrategy, do you have some documentation you can point me at so I can better understand the feature.

At this point Grace supports the decorator pattern that some people use for interception. [Here](https://github.com/ipjohnson/Grace/blob/master/tests/Grace.Tests/DependencyInjection/Intercept/InterceptionTests.cs) are some of the unit test where I'm using Castle Core for interception (Note: the Interception extension is not part of Grace it's found [here](https://github.com/ipjohnson/Grace/blob/master/tests/Grace.Tests/DependencyInjection/Intercept/InterceptionExtensions.cs)

As interception is a pretty large topic some specifics might help. Are you doing your own interception or using a library like Castle Core?

**Comment by ILAgent** [comment]
Thank you, I've seen. But I'd like to intercept pre and post build moments for all services in my container. In Unity I can do it such:
```


 public class MyExtension : UnityContainerExtension
    {
        protected override void Initialize()
        {
            Context.Strategies.Add(new TimerStrategy(), UnityBuildStage.PreCreation);
        }

        private class MyStrategy : BuilderStrategy
        {
            public override void PostBuildUp(IBuilderContext context)
            {
            }

            public override void PreBuildUp(IBuilderContext context)
            {
            }
        }
    }
```

Also example is here http://mark-dot-net.blogspot.ru/2009/09/custom-object-factory-unity-extension.html

I haven't understood, how to implement it with Grace.

**Comment by ipjohnson** [comment]
@ILAgent I'm going to be honest with you Grace wasn't built with this type of use case in mind because it's really slow to execute at request time. 

Grace essentially builds delegates on the fly that look something like this
```
private object CreationDelegateForSomeClass(scope, disposalScope, injectionContext)
{
  return new SomeClass(new SomeDependency(), new SomeOtherDependency); 
}
```
Grace supports the idea of post build up with decorators but no PreBuildUp. With some work you can probably mimic the behaviors you're looking for but it's not out of the box. For example the article you linked to talks about using it for caching where as in Grace you'd just create your own lifestyle that implements caching. 

Out of curiosity what is it you do with the pre and post that's the same for all objects? Some type of logging?

**Comment by ILAgent** [comment]
Yes, I have to log resloving time for each service, so I need to measure intervals between pre and post build moments. Is it possible with Grace ?

**Comment by ipjohnson** [comment]
@ILAgent sorry it's not really possible at this point in time, that said with the way top performing containers (Grace, DryIoc, lightinject, etc)  are written you're going to spend far more time trying to time the instantiation than it takes to actually instantiate the object. 

Performance [numbers](http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison) show that 
* Untity is ~300x slower than grace (that's without doing any pre-post build up)
* it take less than 100 milliseconds to instantiate 1.5 million objects on a low powered laptop.

I'm not saying Grace is for you or that it will solve all your issues but instantiation performance is probably not one of the problems you will have with Grace

**Comment by ipjohnson** [comment]
Sorry I did the math wrong untity for the complex use case is 450x slower than grace.

**Comment by ILAgent** [comment]
Thank you, perfomance is general reason why I'm looking to Grace. But unfortunately my services have complex constructors and must be profiled...

**Comment by ipjohnson** [comment]
@ILAgent it's possible to time a whole object graph being constructed but at this point I don't really see a good way to add the feature on a per instatiation basis and keep things performant.

Wish I had a better answer for you but part of the reason Grace is as fast as it is, is because it's not quite as dynamic as Untity and NInject (No pre-build up only post).

**Comment by ipjohnson** [comment]
@ILAgent I thought about it some more and maybe there is a way to do what you are looking to do. I've refactored the constructor logic recently for issue #78 and I think maybe something like this could work for your situation

[Custom constructor logic](https://github.com/ipjohnson/Grace/blob/master/tests/Grace.Tests/DependencyInjection/ConstructorSelection/TimedConstructorSelectionMethod.cs)

I'd consider formalizing it if it works for you.

**Comment by ipjohnson** [comment]
@ILAgent were you able to get this solution working or have you moved onto another container?

**Comment by ILAgent** [comment]
Hi ! I've found too difficult to change ioc container in my project, that's why I have not tried yet.

**Comment by ipjohnson** [comment]
Completely understand. Depending on how it's built it's like trying to replace your house's foundation while still living in it.

I think for moment I'm going to close this issue, then in a couple months when I have some more time I'll open a new issue for implementing this feature as it does seem interesting just not something I can implement now (I official have less than 5 weeks to finish some pressing issues before the new born arrives)

**Comment by ILAgent** [comment]
Thank you ! Hope I'll try Grace in the nearest future.
