### ISSUE TITLE
Is there support for metadata available ?

### ISSUE THREAD

**Issue by crystalbyte** [ipjohnson/Grace#85]
Is there currently a way to publish and distinguish multiple exports of the same type ?

**Comment by ipjohnson** [comment]
hi @crystalbyte yes there is support for metadata there is a built in class in Grace called `Meta<T>` it functions similarly to Autofac and other containers. 

You can check out some of the unit tests [here](https://github.com/ipjohnson/Grace/blob/master/tests/Grace.Tests/DependencyInjection/Metadata/MetadataTests.cs). If you have an questions or looking for some enhancements let me know.

**Comment by crystalbyte** [comment]
Thanks for the quick feedback.

**Comment by ipjohnson** [comment]
One place that I could see enhancing the metadata would be to add `Meta<T, TMetadata>` where the properties of TMetadata are bound to metadata properties. I think ninject has something like this.
