### ISSUE TITLE
Depricate ExportInstance(delegate) methods in favor of ExportFactory<...> methods

### ISSUE THREAD

**Issue by ipjohnson** [ipjohnson/Grace#89]
With the introduction of the ExportFactory method the ExportInstance(delegate) methods have become obsolete. As well as being obsolete the behavior is not consistent with how `ExportInstance<T>(T value)` and leads to confusion as seen in issue #86. With this in mind I'm going to mark the methods as obsolete in 6.2 and plan to remove them at some point later for a major version number release.

**Comment by darkcamper** [comment]
@ipjohnson How about adding an "ExportFuncWithContext<T>" extension method (that maps to ExportFunc<IExportLocatorScope, StaticInjectionContext, IInjectionContext,T>) to IExportRegistrationBlock? 

I think it would make easier the transition from the obsolete ExportInstance method when you just want to do a context-base activation, and would provide design-time support for tools such as Resharper to suggest you the signature of the delegate.

**Comment by ipjohnson** [comment]
@darkcamper sounds like a good idea, something like this?

```
public static IFluentExportInstanceConfiguration<T> ExportFuncWithContext<T>(
     this IExportRegistrationBlock block, 
     Func<IExportLocatorScope, StaticInjectionContext, IInjectionContext,T> func)
{
   return block.ExportFactory(func);
}
```
