### ISSUE TITLE
Extend support for special types

### ISSUE THREAD

**Issue by darkcamper** [ipjohnson/Grace#91]
I've noticed that you can automatically Locate an IEnumerable<Func<T>> but not an Func<IEnumerable<T>> (or at least I've been unable to make it work). 

I think it would make sense when you want to declare a dependency on a single factory that returns all known exports for T.

```c#
public MyClass(Func<IEnumerable<IWhatEver>> knownWhateverFactory)
```

**Comment by ipjohnson** [comment]
So looking at this it's definitely a bug. It has to do with the way wrappers are calculated and the fact `IEnumerable<T>` and `T[]` don't have activation strategies.
